"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
import rollbar
from pathlib import Path
from urllib.parse import unquote, urlsplit

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_TESTING = os.getenv("PYTEST_CURRENT_TEST") is not None


def _to_bool(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    return value.lower() in ("true", "1", "yes")


def _sqlite_db_config(url: str, conn_max_age: int = 600) -> dict:
    """Формирует конфигурацию для sqlite, не требуя dj-database-url."""
    split_result = urlsplit(url)
    # urlsplit оставляет путь пустым для вида sqlite://db.sqlite3, поэтому учитываем netloc.
    path = unquote(split_result.path) or unquote(split_result.netloc)
    if not path:
        path = str(BASE_DIR / 'db.sqlite3')
    # На Windows absolute path выглядит как /C:/..., поэтому удаляем ведущий слэш.
    if os.name == 'nt' and path.startswith('/') and len(path) > 2 and path[2] == ':':
        path = path[1:]
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": path,
        "CONN_MAX_AGE": conn_max_age,
    }


# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv("SECRET_KEY") or os.getenv("DJANGO_SECRET_KEY")
SECRET_KEY = _secret_key or "dev-secret-key"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _to_bool(os.getenv("DEBUG") or os.getenv("DJANGO_DEBUG"), default=False)

_default_allowed_hosts = {
    "localhost",
    "127.0.0.1",
    "webserver",
    ".onrender.com",
}
allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
allowed_hosts = {
    host.strip()
    for host in allowed_hosts_env.split(",")
    if host.strip()
}
ALLOWED_HOSTS = sorted(_default_allowed_hosts | allowed_hosts)


def _host_to_csrf_origins(host: str) -> set[str]:
    host = host.strip()
    if not host:
        return set()
    if host.startswith("."):
        trimmed = host[1:]
        if not trimmed:
            return set()
        target = f"*.{trimmed}"
    else:
        target = host
    return {
        f"http://{target}",
        f"https://{target}",
    }


_default_csrf_trusted_origins = {
    "http://localhost",
    "https://localhost",
    "http://127.0.0.1",
    "https://127.0.0.1",
}
_csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
_csrf_extra_origins = {
    origin.strip()
    for origin in _csrf_env.split(",")
    if origin.strip()
}
_csrf_from_hosts = set()
for host in ALLOWED_HOSTS:
    _csrf_from_hosts.update(_host_to_csrf_origins(host))
CSRF_TRUSTED_ORIGINS = sorted(
    _default_csrf_trusted_origins | _csrf_extra_origins | _csrf_from_hosts
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'task_manager',
    'task_manager.users',
    'task_manager.statuses',
    'task_manager.tasks',
    'task_manager.labels',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'task_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "task_manager" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_manager.wsgi.application'


# Database
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")

if IS_TESTING:
    test_db_url = os.getenv(
        "TEST_DATABASE_URL",
        f"sqlite:///{BASE_DIR / 'test_db.sqlite3'}",
    )
    DATABASES = {"default": _sqlite_db_config(test_db_url)}
elif DATABASE_URL.startswith("sqlite"):
    DATABASES = {"default": _sqlite_db_config(DATABASE_URL)}
else:
    try:
        import dj_database_url  # type: ignore
    except ModuleNotFoundError as exc:  # pragma: no cover - требуется только вне dev-окружения
        raise ImproperlyConfigured(
            "Install dj-database-url to work with non-sqlite databases."
        ) from exc
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
USE_I18N = True
USE_TZ = True

LANGUAGE_CODE = 'ru'
LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
os.makedirs(STATIC_ROOT, exist_ok=True)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

_ROLLBAR_ACCESS_TOKEN = os.getenv('ROLLBAR_ACCESS_TOKEN', '').strip()
_ROLLBAR_ENV = os.getenv('ROLLBAR_ENV', 'development')
_ROLLBAR_CODE_VERSION = os.getenv('ROLLBAR_CODE_VERSION', '1.0')

ROLLBAR = None

if _ROLLBAR_ACCESS_TOKEN:
    ROLLBAR = {
        'access_token': _ROLLBAR_ACCESS_TOKEN,
        'environment': _ROLLBAR_ENV,
        'code_version': _ROLLBAR_CODE_VERSION,
        'root': BASE_DIR,
    }
    rollbar.init(**ROLLBAR)
    MIDDLEWARE.append('task_manager.rollbar_middleware.CustomRollbarNotifierMiddleware')
