#!/usr/bin/env bash
set -euo pipefail

# Install uv (package manager)
curl -LsSf https://astral.sh/uv/install.sh | sh

# Windows installer does not create the env script; fall back to updating PATH.
if [[ -f "$HOME/.local/bin/env" ]]; then
  # shellcheck disable=SC1090 # file is generated by the uv installer
  source "$HOME/.local/bin/env"
else
  export PATH="$HOME/.local/bin:$PATH"
fi

# Install dependencies & prepare project.
make install && make collectstatic
