# Generated by Django 5.2.4 on 2025-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Label", "verbose_name_plural": "Labels"},
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
