# Generated by Django 5.2.4 on 2025-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
